version: 2

aliases:
  containers:
    docker: &DEFAULT
      - image: jesiio/jesi:0.3
     - image: jesiio/docker-git-awscli:latest

jobs:
  test:
    docker: *DEFAULT
    steps:
      - checkout
      - run: './cancel-redundant-builds.sh'
      - run: 'sleep 1m'
      - run: './cancel-redundant-builds.sh'
      - run: 'sleep 1m'
      - run: './cancel-redundant-builds.sh'
      - run: 'sleep 1m'

workflows:
  version: 2
  build:
    jobs:
      - test
