version: 2

jobs:
  build:
    docker:
      - image: jesiio/docker-git-awscli:latest
    steps:
      - checkout
      - run: './cancel-redundant-builds.sh'
      - run: 'sleep 1m'
      - run: './cancel-redundant-builds.sh'
      - run: 'sleep 1m'
      - run: './cancel-redundant-builds.sh'
      - run: 'sleep 1m'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
